name: EIDIKO-ACE-CI
on:
  push:
    branches: [ main ]
env:
 BAR_STORE: Sum_API\target\ace\Sum_API-1.0.0.bar
 BAR_STORE-1: target\SamplApp-1.0.bar
jobs:
  ACE-CI:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: List Folder
        run: |
          ls
      - name: Building bar file for SamplApp
        run: |
          mvn clean package
      - name: Building bar file for Java_LIB
        run: |
          mvn clean package -f Java_LIB/pom.xml
      - name: Building bar file for Calculator_LIB
        run: |
          mvn clean package -f Calculator_LIB/pom.xml
      - name: Building bar file for Sum_API
        run: |
          mvn clean package -f Sum_API/pom.xml
      - name: Modules Build
        run: |
          mvn clean package -f complete-build.xml
      - name: Running Test Cases
        run: |
          mvn clean package -f AceTesting/pom.xml          
      - name: Upload bar file ZIP package
        uses: actions/upload-artifact@v2
        with:
          name: ace-package
          path: ${{ env.BAR_STORE }}
  ACE-DEV-TEST:
    needs: [ACE-CI]
    runs-on: self-hosted
    environment: 
      name: DEV
    steps:
      - name: Checkout Current Repo
        uses: actions/checkout@v2
      - name: Download and Extract bar file
        uses: actions/download-artifact@v2
        with:
          name: ace-package
          path: ${{ runner.workspace }}/downloaded-artifact
      - name: List Downloaded Folder
        run: |
          ls ${{ runner.workspace }}/downloaded-artifact  
      - name: Deploy on DEV
        run: |
          mvn clean package -f deploy-pom.xml           
      - name: Running Test Cases on DEV
        run: |
          mvn clean package -f AceTesting/pom.xml         
  ACE-UAT-TEST:
    needs: [ACE-DEV-TEST]
    runs-on: self-hosted
    environment: 
      name: UAT
    steps:
      - name: Checkout Current Repo
        uses: actions/checkout@v2
      - name: Download and Extract bar file
        uses: actions/download-artifact@v2
        with:
          name: ace-package
          path: ${{ runner.workspace }}/downloaded-artifact
      - name: List Downloaded Folder
        run: |
          ls ${{ runner.workspace }}/downloaded-artifact  
      - name: Deploy on UAT
        run: |
          mvn clean package -f deploy-pom.xml           
      - name: Running Test Cases on UAT
        run: |
          mvn clean package -f AceTesting/pom.xml
  ACE-PROD-TEST:
    needs: [ACE-UAT-TEST]
    runs-on: self-hosted
    environment: 
      name: PROD
    steps:
      - name: Checkout Current Repo
        uses: actions/checkout@v2
      - name: Download and Extract bar file
        uses: actions/download-artifact@v2
        with:
          name: ace-package
          path: ${{ runner.workspace }}/downloaded-artifact
      - name: List Downloaded Folder
        run: |
          ls ${{ runner.workspace }}/downloaded-artifact  
      - name: Deploy on PROD
        run: |
          mvn clean package -f deploy-pom.xml          
      - name: Running Test Cases on PROD
        run: |
          mvn clean package -f AceTesting/pom.xml