name: EIDIKO-ACE-CI
on:
  push:
    branches: [ main ]
env:
 BAR_STORE: target\SamplApp-1.0.bar
jobs:
  ACE-CI:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: List Folders
        run: |
          ls
      - name: Building bar file
        run: |
          mvn clean package
      - name: Running Test Cases
        run: |
          mvn clean package -f AceTesting/pom.xml          
      - name: Upload bar file ZIP package
        uses: actions/upload-artifact@v2
        with:
          name: ace-package
          path: ${{ env.BAR_STORE }}
