name: EIDIKO-ACE-CI
on:
  push:
    branches: [ main ]
env:
 BAR_STORE: SamplApp-1.0.bar
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Building bar file
        run: mvn clean package
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: samplapp-package
          path: ${{ env.BAR_STORE }}
